/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class frmMain extends javax.swing.JFrame {
 private DefaultTableModel model = new DefaultTableModel();
    String tglpinjam;
    
    private void TglPinjamPropertyChange(java.beans.PropertyChangeEvent evt){
        if(tglpinjam1.getDate()!=null){
        SimpleDateFormat Format=new SimpleDateFormat("dd-MM-YYYY");
        tglpinjam=Format.format(tglpinjam1.getDate());
        
        }
    }
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtNama1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat1 = new javax.swing.JTextArea();
        txtNo1 = new javax.swing.JTextField();
        tglpinjam1 = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnNovel = new javax.swing.JRadioButton();
        txtId1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnBelum = new javax.swing.JRadioButton();
        btnKamus = new javax.swing.JRadioButton();
        btnKomik = new javax.swing.JRadioButton();
        txtJudul1 = new javax.swing.JTextField();
        btnKembali = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnClear2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtId2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtNama2 = new javax.swing.JTextField();
        txtAlamat2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtJenis = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtTglPinjam = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtDenda = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnSimpan1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        btnRefresh1 = new javax.swing.JButton();
        btnClear1 = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        btnQuit1 = new javax.swing.JButton();
        tglKembali = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        txtNo2 = new javax.swing.JTextField();
        btnClear3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        jLabel13.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel13.setText("ALAMAT");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 150, 100, 20);

        txtNama1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtNama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNama1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtNama1);
        txtNama1.setBounds(130, 100, 180, 30);

        jLabel17.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel17.setText("NAMA");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 110, 130, 20);

        jLabel18.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel18.setText("JENIS");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(20, 300, 110, 20);

        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pinjam", "No Anggota", "Nama", "Alamat", "Tgl Pinjam", "Jenis", "Judul", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(340, 10, 580, 200);

        btnSimpan.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        btnSimpan.setText("SAVE");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan);
        btnSimpan.setBounds(380, 230, 110, 40);

        btnDelete.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);
        btnDelete.setBounds(380, 280, 110, 40);

        btnRefresh.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh);
        btnRefresh.setBounds(510, 280, 110, 40);

        btnClear.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(510, 230, 110, 40);

        btnEdit.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);
        btnEdit.setBounds(630, 230, 110, 40);

        btnQuit.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        btnQuit.setText("QUIT");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuit);
        btnQuit.setBounds(630, 280, 110, 40);

        txtAlamat1.setColumns(20);
        txtAlamat1.setRows(5);
        jScrollPane1.setViewportView(txtAlamat1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 150, 180, 96);

        txtNo1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNo1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtNo1);
        txtNo1.setBounds(130, 60, 180, 30);
        jPanel1.add(tglpinjam1);
        tglpinjam1.setBounds(130, 260, 180, 30);

        jLabel26.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel26.setText("TGL PINJAM");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(20, 260, 110, 20);

        jLabel27.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel27.setText("ID PINJAM");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(20, 30, 110, 20);

        buttonGroup1.add(btnNovel);
        btnNovel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovel.setText("NOVEL");
        btnNovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovelActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovel);
        btnNovel.setBounds(130, 300, 100, 30);

        txtId1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtId1);
        txtId1.setBounds(130, 20, 180, 30);

        jLabel28.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel28.setText("NO ANGGOTA");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(20, 70, 110, 20);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        buttonGroup3.add(btnBelum);
        btnBelum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBelum.setText("Belum Kembali");
        jPanel4.add(btnBelum);
        btnBelum.setBounds(120, 490, 140, 30);

        buttonGroup1.add(btnKamus);
        btnKamus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKamus.setText("KAMUS");
        jPanel4.add(btnKamus);
        btnKamus.setBounds(120, 370, 100, 30);

        buttonGroup1.add(btnKomik);
        btnKomik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKomik.setText("KOMIK");
        jPanel4.add(btnKomik);
        btnKomik.setBounds(120, 330, 110, 30);

        txtJudul1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtJudul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJudul1ActionPerformed(evt);
            }
        });
        jPanel4.add(txtJudul1);
        txtJudul1.setBounds(120, 410, 180, 30);

        buttonGroup3.add(btnKembali);
        btnKembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKembali.setText("Kembali");
        jPanel4.add(btnKembali);
        btnKembali.setBounds(120, 450, 100, 30);

        jLabel25.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel25.setText("STATUS");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(10, 450, 110, 20);

        jLabel29.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel29.setText("JUDUL");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(10, 410, 110, 20);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 10, 320, 530);

        btnClear2.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        btnClear2.setText("PRINT");
        btnClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear2);
        btnClear2.setBounds(380, 330, 360, 40);

        jTabbedPane1.addTab("PEMINJAMAN", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel10.setText("ID PINJAM");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 20, 120, 20);

        txtId2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtId2);
        txtId2.setBounds(130, 20, 150, 30);

        jLabel19.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel19.setText("NAMA");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(20, 130, 90, 20);

        txtNama2.setEditable(false);
        txtNama2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtNama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNama2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtNama2);
        txtNama2.setBounds(130, 120, 150, 30);

        txtAlamat2.setEditable(false);
        txtAlamat2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtAlamat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamat2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtAlamat2);
        txtAlamat2.setBounds(130, 160, 150, 30);

        jLabel20.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel20.setText("ALAMAT");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(20, 170, 130, 20);

        jLabel21.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel21.setText("JUDUL");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(20, 250, 100, 20);

        txtJenis.setEditable(false);
        txtJenis.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisActionPerformed(evt);
            }
        });
        jPanel2.add(txtJenis);
        txtJenis.setBounds(130, 200, 150, 30);

        jLabel22.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel22.setText("JENIS");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(20, 210, 100, 20);

        txtTglPinjam.setEditable(false);
        txtTglPinjam.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtTglPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTglPinjamActionPerformed(evt);
            }
        });
        jPanel2.add(txtTglPinjam);
        txtTglPinjam.setBounds(440, 90, 150, 30);

        jLabel23.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel23.setText("TGL KEMBALI");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(320, 130, 130, 20);

        txtJudul.setEditable(false);
        txtJudul.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJudulActionPerformed(evt);
            }
        });
        jPanel2.add(txtJudul);
        txtJudul.setBounds(130, 240, 150, 30);

        jLabel24.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel24.setText("TGL PINJAM");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(320, 90, 100, 20);

        jButton1.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jButton1.setText("CARI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(300, 20, 100, 40);

        txtDenda.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDendaActionPerformed(evt);
            }
        });
        jPanel2.add(txtDenda);
        txtDenda.setBounds(440, 170, 150, 30);

        jTable2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Pinjam", "No Anggota", "Nama", "Alamat", "Tgl Pinjam", "Jenis", "Judul", "Tgl Kembali", "Denda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(20, 310, 760, 220);

        btnSimpan1.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        btnSimpan1.setText("SAVE");
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan1);
        btnSimpan1.setBounds(300, 210, 110, 40);

        btnDelete1.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        btnDelete1.setText("DELETE");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete1);
        btnDelete1.setBounds(300, 250, 110, 40);

        btnRefresh1.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        btnRefresh1.setText("REFRESH");
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnRefresh1);
        btnRefresh1.setBounds(440, 250, 110, 40);

        btnClear1.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        btnClear1.setText("CLEAR");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear1);
        btnClear1.setBounds(440, 210, 110, 40);

        btnEdit1.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        btnEdit1.setText("EDIT");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnEdit1);
        btnEdit1.setBounds(580, 210, 110, 40);

        btnQuit1.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        btnQuit1.setText("QUIT");
        btnQuit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuit1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnQuit1);
        btnQuit1.setBounds(580, 250, 110, 40);
        jPanel2.add(tglKembali);
        tglKembali.setBounds(440, 130, 150, 30);

        jLabel15.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel15.setText("DENDA");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(320, 170, 100, 20);

        txtNo2.setEditable(false);
        txtNo2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNo2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtNo2);
        txtNo2.setBounds(130, 80, 150, 30);

        btnClear3.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        btnClear3.setText("PRINT");
        btnClear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear3);
        btnClear3.setBounds(700, 210, 130, 80);

        jLabel11.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel11.setText("NO ANGGOTA");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 80, 120, 20);

        jTabbedPane1.addTab("PENGEMBALIAN", jPanel2);

        jPanel5.add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 90, 930, 590);

        jLabel1.setFont(new java.awt.Font("KG Blank Space Solid", 0, 24)); // NOI18N
        jLabel1.setText("PERPUSTAKAAN KOTA MALANG");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(260, 30, 440, 50);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 980, 700);

        setSize(new java.awt.Dimension(992, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNama1ActionPerformed

    private void txtJudul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudul1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudul1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.getSelectedRow();
        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
        Date dateValue = null;
        try {
            dateValue = date.parse((String) jTable1.getValueAt(baris, 4));
        } catch (ParseException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (baris != 1) {
            txtId1.setText(jTable1.getValueAt(baris, 0).toString());
            txtNo1.setText(jTable1.getValueAt(baris, 1).toString());
            txtNama1.setText(jTable1.getValueAt(baris, 2).toString());
            txtAlamat1.setText(jTable1.getValueAt(baris, 3).toString());
            tglpinjam1.setDate(dateValue);
            if ("Novel".equals(jTable1.getValueAt(baris, 5).toString())) {
                btnNovel.setSelected(true);
            } else if ("Komik".equals(jTable1.getValueAt(baris, 5).toString())){
                btnKomik.setSelected(true);
            } else {
                btnKamus.setSelected(true);
            }
            
            txtJudul1.setText(jTable1.getValueAt(baris, 6).toString());
            if ("Kembali".equals(jTable1.getValueAt(baris, 7).toString())) {
                btnKembali.setSelected(true);
            } else {
                btnBelum.setSelected(true);
            }
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if ("".equals(txtId1.getText()) ||"".equals(txtNo1.getText()) || "".equals(txtJudul1.getText()) || "".equals(txtNama1.getText()) ||"".equals(tglpinjam1.getDate()) || "".equals(txtAlamat1.getText())) {
            jOptionPane1.showMessageDialog(this, "Harap Lengkapi Data", "Error", jOptionPane1.WARNING_MESSAGE);
        } else {
             String jenis = "";
                if (btnNovel.isSelected()) {
                    jenis = "Novel";
                } else if (btnKomik.isSelected()){
                    jenis = "Komik";
                } else {
                    jenis = "Kamus";
                }

            String statuskembali = "";
                if (btnKembali.isSelected()) {
                    statuskembali = "Kembali";
                } else {
                    statuskembali = "Belum Kembali";
                }
            SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
            String tgl = date.format(tglpinjam1.getDate());

            String SQL = "INSERT INTO peminjaman " + "VALUES('" + txtId1.getText() + "','" + txtNo1.getText() + "','" + txtNama1.getText() + "', '" + txtAlamat1.getText() + "','"+tgl+"','" + jenis + "','" + txtJudul1.getText() + "','" + statuskembali + "')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1){
                jOptionPane1.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", jOptionPane1.INFORMATION_MESSAGE);
                selectData();
            } else {
                jOptionPane1.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", jOptionPane1.WARNING_MESSAGE);
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    public void selectData(){
        String kolom[] = {"id_pinjam","no_anggota","nama","alamat","tgl_pinjam","jenis","judul","status"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM peminjaman";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        
        try {
            while(rs.next()){
                String id_pinjam = rs.getString(1);
                String no_anggota = rs.getString(2);
                String nama = rs.getString(3);
                String alamat = rs.getString(4);
                String tgl_pinjam = rs.getString(5);
                String jenis = "";
                if ("Novel".equals(rs.getString(6))) {
                    jenis = "Novel";
                } else if ("Komik".equals(rs.getString(6))){
                    jenis = "Komik";
                } else {
                    jenis = "Kamus";
                }
                String judul = rs.getString(7);
                String statuskembali = "";
                if ("Kembali".equals(rs.getString(8))) {
                    statuskembali = "Kembali";
                } else {
                    statuskembali = "Belum Kembali";
                }
                String data[] = {id_pinjam,no_anggota,nama,alamat,tgl_pinjam,jenis,judul,statuskembali};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(dtm);
    }
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int baris = jTable1.getSelectedRow();
        if(baris != -1) {
            String id_pinjam = jTable1.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM peminjaman WHERE id_pinjam='"+id_pinjam+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                jOptionPane1.showMessageDialog(this, "Data berhasil dihapus", "Sukses", jOptionPane1.INFORMATION_MESSAGE);
            } else {
                jOptionPane1.showMessageDialog(this, "Data gagal dihapus", "Gagal", jOptionPane1.WARNING_MESSAGE);
            }
        } else {
            jOptionPane1.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", jOptionPane1.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        selectData();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtNo1.setText("");
        txtNama1.setText("");
        txtAlamat1.setText("");
        buttonGroup1.clearSelection();
        txtJudul1.setText("");
        tglpinjam1.setDate(null);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if ("".equals(txtId1.getText()) ||"".equals(txtNo1.getText()) || "".equals(txtNama1.getText()) ||"".equals(txtAlamat1.getText()) || "".equals(tglpinjam) || "".equals(txtJudul1.getText())) {
            jOptionPane1.showMessageDialog(this, "Harap Lengkapi Data", "Error", jOptionPane1.WARNING_MESSAGE);
        } else {
            String jenis = "";
            if (btnNovel.isSelected()) {
                jenis = "Novel";
            } else if (btnKomik.isSelected()){
                jenis = "Komik";
            } else {
                jenis = "Kamus";
            }

            String statuskembali = "";
                if (btnKembali.isSelected()) {
                    statuskembali = "Kembali";
                } else {
                    statuskembali = "Belum Kembali";
                }
            
            SimpleDateFormat date = new SimpleDateFormat("dd-MM-YYYY");
            String tgl = date.format(tglpinjam1.getDate());

            String SQL = "UPDATE peminjaman SET "
            + "id_pinjam='"+txtId1.getText()+"', "
            + "no_anggota='"+txtNo1.getText()+"', "
            + "nama='"+txtNama1.getText()+"', "
            + "alamat='"+txtAlamat1.getText()+"', "
            + "tgl_pinjam='"+tgl+"', "
            + "jenis='"+jenis+"', "
            + "judul='"+txtJudul1.getText()+"', "
            + "status='"+statuskembali+"' WHERE no_anggota='"+txtNo1.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                jOptionPane1.showMessageDialog(this, "Data berhasil diupdate", "Sukses", jOptionPane1.INFORMATION_MESSAGE);
                selectData();
            } else {
                jOptionPane1.showMessageDialog(this, "Data gagal diupdate", "Sukses", jOptionPane1.WARNING_MESSAGE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitActionPerformed

    private void txtId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId2ActionPerformed

    private void txtNama2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNama2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNama2ActionPerformed

    private void txtAlamat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamat2ActionPerformed

    private void txtJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisActionPerformed

    private void txtTglPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglPinjamActionPerformed

    private void txtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            String SQL = "SELECT * FROM peminjaman WHERE id_pinjam='"+txtId2.getText()+"'";
            ResultSet rs = KoneksiDB.executeQuery(SQL);
            while (rs.next()) {
                txtNo2.setText(rs.getString(2));
                txtNama2.setText(rs.getString(3));
                txtAlamat2.setText(rs.getString(4));
                txtTglPinjam.setText(rs.getString(5));
                txtJenis.setText(rs.getString(6));
                txtJudul.setText(rs.getString(7));

            }

        } catch (Exception e){
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDendaActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int baris = jTable2.getSelectedRow();
        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
        Date dateValue2 = null;
        try {
            dateValue2 = date.parse((String) jTable2.getValueAt(baris, 7));
        } catch (ParseException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (baris != 1) {
            txtId2.setText(jTable2.getValueAt(baris, 0).toString());
            txtNo2.setText(jTable2.getValueAt(baris, 1).toString());
            txtNama2.setText(jTable2.getValueAt(baris, 2).toString());
            txtAlamat2.setText(jTable2.getValueAt(baris, 3).toString());
            txtTglPinjam.setText(jTable2.getValueAt(baris, 4).toString());
            txtJenis.setText(jTable2.getValueAt(baris, 5).toString());
            txtJudul.setText(jTable2.getValueAt(baris,6).toString());
            tglKembali.setDate(dateValue2);
            txtDenda.setText(jTable2.getValueAt(baris, 8).toString());
             
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
        if ("".equals(tglKembali.getDate()) || "".equals(txtDenda.getText())) {
            jOptionPane1.showMessageDialog(this, "Harap Lengkapi Data", "Error", jOptionPane1.WARNING_MESSAGE);
        } else {
            
                    
            
            
            SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
            String tgl2 = date.format(tglKembali.getDate());

            String SQL = "INSERT INTO pengembalian " + "VALUES('" + txtId2.getText() + "', '" + txtNo2.getText() + "','" + txtNama2.getText() + "','" + txtAlamat2.getText() + "','"+txtTglPinjam.getText()+"','"+txtJenis.getText()+"','" + txtJudul.getText() + "','" + tgl2 + "','" + txtDenda.getText() + "')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1){
                jOptionPane1.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", jOptionPane1.INFORMATION_MESSAGE);
                selectData();
            } else {
                jOptionPane1.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", jOptionPane1.WARNING_MESSAGE);
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpan1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        int baris = jTable2.getSelectedRow();
        if(baris != -1) {
            String id_pinjam = jTable2.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM pengembalian WHERE id_pinjam='"+id_pinjam+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                jOptionPane1.showMessageDialog(this, "Data berhasil dihapus", "Sukses", jOptionPane1.INFORMATION_MESSAGE);
            } else {
                jOptionPane1.showMessageDialog(this, "Data gagal dihapus", "Gagal", jOptionPane1.WARNING_MESSAGE);
            }
        } else {
            jOptionPane1.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", jOptionPane1.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        selectData2();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefresh1ActionPerformed

     public void selectData2(){
        String kolom[] = {"id_pinjam","no_anggota","nama","alamat","tgl_pinjam","jenis","judul","tgl_kembali","denda"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM pengembalian";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()){
                String id_pinjam = rs.getString(1);
                String no_anggota = rs.getString(2);
                String nama = rs.getString(3);
                String alamat = rs.getString(4);
                String tgl_pinjam = rs.getString(5);
                String jenis = rs.getString(6);
                String judul = rs.getString(7);
                String tgl_kembali = rs.getString(8);
                String denda = rs.getString(9);
                
                String data[] = {id_pinjam,no_anggota,nama,alamat,tgl_pinjam,jenis,judul,tgl_kembali,denda};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable2.setModel(dtm);
    }
    
    
    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        txtId2.setText("");
        txtNo2.setText("");
        txtNama2.setText("");
        txtAlamat2.setText("");
        txtJenis.setText("");
        txtTglPinjam.setText("");
        txtJudul.setText("");
        tglKembali.setDate(null);
        txtDenda.setText("");
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        if ("".equals(txtId2.getText()) || "".equals(txtNama2.getText()) || "".equals(txtAlamat2.getText()) || "".equals(txtTglPinjam.getText()) || "".equals(txtJenis.getText()) || "".equals(tglKembali.getDate()) || "".equals(txtDenda.getText())|| "".equals(txtJudul.getText())) {
            jOptionPane1.showMessageDialog(this, "Harap Lengkapi Data", "Error", jOptionPane1.WARNING_MESSAGE);
        } else {
            
            
            
            SimpleDateFormat date = new SimpleDateFormat("dd-MM-YYYY");
            String tgl2 = date.format(tglKembali.getDate());

            String SQL = "UPDATE pengembalian SET "
            + "id_pinjam='"+txtId2.getText()+"', "
            + "no_anggota='"+txtNo2.getText()+"', "
            + "nama='"+txtNama1.getText()+"', "
            + "alamat='"+txtAlamat2.getText()+"', "
            + "tgl_pinjam='"+txtTglPinjam.getText()+"', "
            + "jenis='"+txtJenis.getText()+"', "
            + "judul='"+txtJudul.getText()+"', "
            + "tgl_kembali='"+tgl2+"', "
            
            + "denda='"+txtDenda.getText()+"' WHERE id_pinjam='"+txtId2.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                jOptionPane1.showMessageDialog(this, "Data berhasil diupdate", "Sukses", jOptionPane1.INFORMATION_MESSAGE);
                selectData();
            } else {
                jOptionPane1.showMessageDialog(this, "Data gagal diupdate", "Sukses", jOptionPane1.WARNING_MESSAGE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnQuit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuit1ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuit1ActionPerformed

    private void txtNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNo1ActionPerformed

    private void btnNovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovelActionPerformed

    private void txtId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId1ActionPerformed

    private void txtNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNo2ActionPerformed

    private void btnClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear2ActionPerformed
        MessageFormat header = new MessageFormat("Form Peminjaman - Perpustakaan Kota Malang");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)       ");
        try {
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear2ActionPerformed

    private void btnClear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear3ActionPerformed
        MessageFormat header = new MessageFormat("Form Peminjaman - Perpustakaan Kota Malang");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)       ");
        try {
            jTable2.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnBelum;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnClear2;
    private javax.swing.JButton btnClear3;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JRadioButton btnKamus;
    private javax.swing.JRadioButton btnKembali;
    private javax.swing.JRadioButton btnKomik;
    private javax.swing.JRadioButton btnNovel;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnQuit1;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSimpan1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private com.toedter.calendar.JDateChooser tglKembali;
    private com.toedter.calendar.JDateChooser tglpinjam1;
    private javax.swing.JTextArea txtAlamat1;
    private javax.swing.JTextField txtAlamat2;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtId2;
    private javax.swing.JTextField txtJenis;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtJudul1;
    private javax.swing.JTextField txtNama1;
    private javax.swing.JTextField txtNama2;
    private javax.swing.JTextField txtNo1;
    private javax.swing.JTextField txtNo2;
    private javax.swing.JTextField txtTglPinjam;
    // End of variables declaration//GEN-END:variables
}
